### ISSUE TITLE
Flathub Verification

### ISSUE THREAD

**Issue by tfuxu** [ranfdev/Geopard#103]
@ranfdev If you are a Flathub package maintainer, you can easily verify Geopard using the [website method](https://docs.flathub.org/docs/for-app-authors/verification#website).

Benefits:
- Users will know that the package is official
- The sketchy looking "Unverified" badge will be replaced by the verified one
![Screenshot from 2024-04-07 21-06-26](https://github.com/ranfdev/Geopard/assets/73042332/3c610b73-5b83-4f81-8287-e47919fb6257)
![Screenshot from 2024-04-07 21-08-17](https://github.com/ranfdev/Geopard/assets/73042332/0a7908eb-4e65-4160-bbd3-052500549c7b)

**Comment by ranfdev** [comment]
Verification code added, it will show up when flathub updates its cache I guess
