### ISSUE TITLE
Navigating to urls or search does not work in External Link page

### ISSUE THREAD

**Issue by bbb651** [ranfdev/Geopard#105]
**Describe the bug**
When you try and navigate to page while in a External Link page is visible, the new page won't appear and the External Link page will stay visible 

**To Reproduce**
1. Navigate to a non gemini url (for example https://example.com/)
2. Navigate to a gemini url
3. Page loading will finish (color will change and it will be added to the undo history) but the External Link view won't go away

**Expected behavior**
The External Link view will disappear and you'll see the new page you navigated to

**Screenshots**
![image](https://github.com/ranfdev/Geopard/assets/53972231/20af703e-5936-4926-96c2-87bcd181f9e3)

**Software info (please complete the following information):**
 - OS: Archlinux x86_64
 - Geopard's Version: 1.4.0

**Additional context**
The bug does not trigger when going back/forward only when navigating to a url/search query

**Comment by tfuxu** [comment]
I think this was fixed in b52d4d0364458a035d64710bc063df368fc973ae, but @ranfdev needs to confirm it, as I'm not sure

**Comment by tfuxu** [comment]
@bbb651 This bug is no longer reproducible in 1.5.0
