### ISSUE TITLE
Unable to run after build.

### ISSUE THREAD

**Issue by dijit** [ranfdev/Geopard#11]
Tested on https://github.com/ranfdev/Geopard/commit/33db318ec1417cb458153e73b4098d37171d8bb2 and release v1.0.1

I'm unable to build and run locally.

Here's my steps to reproduce:

```
curl -Lo Geopard-1.0.1.tar.gz https://github.com/ranfdev/Geopard/archive/refs/tags/v1.0.1.tar.gz
tar xf Geopard-1.0.1.tar.gz
cd Geopard-1.0.1
meson build
cd build
ninja
./src/release/geopard
```

Error:
```
thread 'main' panicked at 'Could not load gresource file: Error { domain: g-file-error-quark, code: 4, message: "Failed to open file “/usr/local/share/geopard/resources.gresource”: open() failed: No such file or directory" }', src/main.rs:67:59
```

manually changing the `RESOURCES_FILE` constant in `src/build_cofnig.rs` isn't changing the error.

**Comment by ranfdev** [comment]
You need to slightly change the command you used and install the generated resources... I don't remember the commands exactly right now.

I suggest you build this using gnome-builder. It will handle everything for you.
