### ISSUE TITLE
Option to disable color-changing

### ISSUE THREAD

**Issue by 1bcb** [ranfdev/Geopard#113]
**Is your feature request related to a problem? Please describe.**
Geopard's behavior of flashing a different color on each site is an accessibility barrier.  While I have no doubt it looks good for some people, using it for a few minutes gives me a headache and eyestrain due to the color changes.

**Describe the solution you'd like**
I'd like an option to disable the color-changing and have a single solid dark background color for all gemini sites.

**Describe alternatives you've considered**
As mentioned above, I can't currently use Geopard at all without significant pain, so my only alternative is to use a different client.  

However, I _want_ to be able to use Geopard, because I do typically like libadwaita apps.  Geopard can also scroll horizontally on very wide ASCII images, which Lagrange and many other clients can't do.

**Comment by tfuxu** [comment]
@1bcb You can disable unique website colors in configuration file. Refer to [this](https://github.com/ranfdev/Geopard?tab=readme-ov-file#how-to-change-settings) part of README to know the file path, open `config.toml` and change `colors` preference value to `false`.

**Comment by 1bcb** [comment]
Thank you!
