### ISSUE TITLE
Geminispace.info has been shut down

### ISSUE THREAD

**Issue by tfuxu** [ranfdev/Geopard#115]
This means that we need to move to another search provider.  I propose TLGS (gemini://tlgs.one/), as in my experience it is a pretty solid search engine.

Also, we probably should replace the aggregator we have in default bookmarks (gemini://rawtext.club:1965/~sloum/spacewalk.gmi), as it too seems to be shut down (as per announcement from gemini://rawtext.club:1965). I think Antenna (gemini://warmedal.se/~antenna/) would be a good replacement for it.

**Comment by TroubleDog54** [comment]
I second this, it's very annoying not to have the search feature available in the address bar. Please fix this ASAP!

**Comment by ranfdev** [comment]
I can hear you, I'm releasing an update soon

**Comment by ranfdev** [comment]
Thanks @tfuxu for suggesting the updated links, I used those in the latest commit

**Comment by TroubleDog54** [comment]
Thanks muchly! When will the update be pushed to Flathub?

**Comment by ranfdev** [comment]
I pushed the update now, it should be available in < 3 hours
