### ISSUE TITLE
Flatpak not Starting

### ISSUE THREAD

**Issue by rebeltaz** [ranfdev/Geopard#118]
**Describe the bug**
Geopard doesn't start either from the Menu or the command line

**To Reproduce**
Either click on Geopard in the Applications>Internet GUI menu 
or run 'flatpak run "flatpak run com.ranfdev.Geopard" from the command line

**Expected behavior**
well... I expect the program to run :shrug:

**Software info (please complete the following information):**
 - OS: Ubuntu 22.04
 - Geopard's Version : 1.6.0
 
**Additional context**
When I try to run the program, I get this error:
```
thread 'main' panicked at src/main.rs:74:17:
called `Result::unwrap()` on an `Err` value: BoolError { message: "Failed to initialize GTK", filename: "/run/build/Geopard/vendor/gtk4/src/rt.rs", function: "gtk4::rt::init", line: 158 }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I saw in Issue #43 that you asked if s/he was "overriding the gtk theme of flatpak apps". I'm not doing that specifically - and I wouldn't even know how - BUT ... I am running gnome-flashback. I am wondering if that is having the same effect as "overriding the gtk theme of flatpak apps"? If so, is there a way that this CAN run without removing gnome-flashback? 

Thanks.

**Comment by tfuxu** [comment]
This is a likely a different issue from that in #43. Could you run Geopard again with `RUST_BACKTRACE=1` prepended to the command?

**Comment by rebeltaz** [comment]
When I run  'RUST_BACKTRACE=1 flatpak run com.ranfdev.Geopard', I get this

```
thread 'main' panicked at src/main.rs:74:17:
called `Result::unwrap()` on an `Err` value: BoolError { message: "Failed to initialize GTK", filename: "/run/build/Geopard/vendor/gtk4/src/rt.rs", function: "gtk4::rt::init", line: 158 }
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I noticed that the suggestion changed from BACKTRACE=1 to BACKTRACE=full, so... I tried that:

```
thread 'main' panicked at src/main.rs:74:17:
called `Result::unwrap()` on an `Err` value: BoolError { message: "Failed to initialize GTK", filename: "/run/build/Geopard/vendor/gtk4/src/rt.rs", function: "gtk4::rt::init", line: 158 }
stack backtrace:
   0:     0x5631f92e7605 - <unknown>
   1:     0x5631f930bb8b - <unknown>
   2:     0x5631f92e4fff - <unknown>
   3:     0x5631f92e73de - <unknown>
   4:     0x5631f92e8699 - <unknown>
   5:     0x5631f92e83dd - <unknown>
   6:     0x5631f92e8b33 - <unknown>
   7:     0x5631f92e8a14 - <unknown>
   8:     0x5631f92e7ac9 - <unknown>
   9:     0x5631f92e8747 - <unknown>
  10:     0x5631f9136ba3 - <unknown>
  11:     0x5631f9137036 - <unknown>
  12:     0x5631f91692e4 - <unknown>
  13:     0x5631f918fc23 - <unknown>
  14:     0x5631f918fc39 - <unknown>
  15:     0x5631f92df410 - <unknown>
  16:     0x5631f9169915 - <unknown>
  17:     0x7f5c3a78408a - <unknown>
  18:     0x7f5c3a78414b - __libc_start_main
  19:     0x5631f91372d5 - <unknown>
  20:                0x0 - <unknown>

```

**Comment by tfuxu** [comment]
That's not really helpful 🫤 I've seen that you created an issue in Lagrange about this too, this sounds like an issue in Flatpak configuration.

Could you download some other app through Flatpak and check if it also crashes on startup?

**Comment by rebeltaz** [comment]
I do have several other apps installed using flatpak - bottles, discord, tellico... they all work with no issues. 🤷‍♂️

**Comment by tfuxu** [comment]
Probably something broke in the Geopard's sandbox runtime, as it panics at the very beginning of the UI code.
Try completely uninstalling Geopard: `flatpak uninstall --delete-data com.ranfdev.Geopard`

**Comment by rebeltaz** [comment]
Oddly, I ran an 'flatpak update' because I was having (a different) trouble getting another gemini browser I was trying (lagrange) to start and I didn't think to try Geopard again until you mentioned it. It's working now, so ... thank you? :lol: I appreciate it.
