### ISSUE TITLE
tab problem

### ISSUE THREAD

**Issue by mskf1383** [ranfdev/Geopard#15]
Hi
Look at this:
![نماگرفت از 2022-05-23 13-00-41](https://user-images.githubusercontent.com/50908329/169777960-a07f6cd3-ee2b-4480-ad0a-e868966ec576.png)

When The window became a bit smaller and page title can't fit in it (Look at the left tab):
![نماگرفت از 2022-05-23 13-00-54](https://user-images.githubusercontent.com/50908329/169778119-c71045d8-7c59-4a52-915e-77835dc5732d.png)

URL in this screenshot: gemini://gemini.circumlunar.space/news/atom.xml
(It is Right-To-Left because my system language is RTL.)

**Comment by ranfdev** [comment]
Could you explain the problem with more details? I don't understand exactly what's wrong.

Is the report about the rendering issue in the tab, that is, the cut at the top of the tab's title?

Thank you

**Comment by mskf1383** [comment]
> Is the report about the rendering issue in the tab, that is, the cut at the top of the tab's title?

Yes. It sometimes happend. But not always! I'm not sure this is bug of Geopard. It can be a LibAdwaita or GTK bug.

I use Debian 11 with gnome 3.38
And installed Geopard from Flathub
