### ISSUE TITLE
Request: link URL tooltip

### ISSUE THREAD

**Issue by mvuets** [ranfdev/Geopard#18]
I often prefer to know where a link leads to before I may want to click it. I'd like to suggest adding a visual cue to help a user understand whither an active/focused link points.

For example, Firefox, Chromium, Liferea, etc. provide a link URL in a status bar upon hovering over a link. Alternatively it may be a tooltip. Here is a (partly contrived) example:

![url-tooltip](https://user-images.githubusercontent.com/72705/169816707-d28f5534-d8b8-4e8f-b8c9-d7c15f48c8bf.png)

Version: 1.1.0.

**Comment by ranfdev** [comment]
Added in commit [22c6c8bc6af1915a8bcb0bc806448cbd0209e85d](https://github.com/ranfdev/Geopard/commit/22c6c8bc6af1915a8bcb0bc806448cbd0209e85d)
