### ISSUE TITLE
Open file links in default apps

### ISSUE THREAD

**Issue by daudix-UFO** [ranfdev/Geopard#23]
for example, somthing like this: gemini://example.org/pictures/picture.jpg or gemini://example.org/videos/video.mp4, now it just not work

**Comment by ranfdev** [comment]
Can you tell me what version of Geopard are you running?
You can retrieve the version by running the following command in your terminal
```
flatpak info com.ranfdev.Geopard
```

**Comment by daudix-UFO** [comment]
1.1.0

**Comment by ranfdev** [comment]
I don't have this problem on 1.1.0 (there was a problem on 1.0.0). I can't reproduce this. Could you give me a valid gemini link which doesn't work for you?
Also, running Geopard from the terminal with
```
flatpak run com.ranfdev.Geopard
```
may give useful infos

**Comment by daudix-UFO** [comment]
sorry for not replying for hour, but here is info:

❯ flatpak run com.ranfdev.Geopard
com.ranfdev.Geopard
thread 'main' panicked at 'Can't access download directory', src/common/mod.rs:8:10
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

for example, here is capsule with videos, GIF and pictures, tested it with gemini proxy and it works, but not working in geopard
[gemini://caolan.uk/workshop/ ](gemini://caolan.uk/workshop/)

**Comment by ranfdev** [comment]
> sorry for not replying for hour

Don't worry. Thank you for helping me debugging this problem.

It's now clear the problem is related to the download folder not being accessible, but I don't know why.

Tomorrow I'll try using running a fedora VM

**Comment by daudix-UFO** [comment]
@ranfdev by running `flatpak run com.ranfdev.Geopard` I saw that app don't have access to download folder, so, by giving app access to all user folders with Flatseal, everything now works just like a charm, sorry for disturbing with this issue

**Comment by daudix-UFO** [comment]
Problem with accessing download probably because I use russian language, and downloads folder named not "Downloads", instead it named "Загрузки"

**Comment by daudix-UFO** [comment]
The fix is to mke app create Gemini folder in downloads on first launch

**Comment by ranfdev** [comment]
> make app create Gemini folder in downloads on first launch

It already did so in v1.1.0. But I guess there was a problem with the flatpak permissions, so the app couldn't create the folder.

Hopefully [v1.1.1](https://github.com/ranfdev/Geopard/releases/tag/v1.1.1) fixes this for new users.

Thank you for reporting this
