### ISSUE TITLE
Handle mouse forward/back buttons

### ISSUE THREAD

**Issue by Gaming4LifeDE** [ranfdev/Geopard#34]
**Is your feature request related to a problem? Please describe.**
I use my forward and back buttons on my mouse a ton and was wondering if you're going to implement them.

**Describe the solution you'd like**
Connect forward/back mouse button signal to the same handler which handle the UI buttons.

**Comment by Gaming4LifeDE** [comment]
Found docs for it i think: https://gtk-rs.org/gtk4-rs/stable/latest/docs/gtk4/prelude/trait.GestureSingleExt.html

**Comment by ranfdev** [comment]
It's already implemented, I just have to make a release with it. Probably today/tomorrow. Wait for v1.2.0
