### ISSUE TITLE
Reload button

### ISSUE THREAD

**Issue by Gaming4LifeDE** [ranfdev/Geopard#38]
**Is your feature request related to a problem? Please describe.**
I've needed to reload websites a lot lately for development and if certain sites are down... I think a reload button would make a ton of sense here.

**Describe the solution you'd like**
A reload button between back/forward and new tab.

**Additional context**
I'd love to help implement it (since it very low hanging fruit) but I really can't understand the code (or rust in general), I really tried to understand it...

**Comment by ranfdev** [comment]
> I really can't understand the code

By the way, it's not your fault. Rust is already hard by itself. Learning GTK and the glib type system also requires time by itself.
Rust + GTK is just complex.

About the reload button: I'll see what I can do tomorrow.

**Comment by Gaming4LifeDE** [comment]
While you're at it, can you hook up F5 and CTRL+R to the reload function, too? It's the absolute standard for web browsers after all and I think conventions like that are good to be imitated.

By the way, thanks for putting up with all the issues I'm opening 😄

**Comment by ranfdev** [comment]
Implemented in commit https://github.com/ranfdev/Geopard/commit/cb595b630ca17456e5688d39b8905218381aacb0
