### ISSUE TITLE
Prepare for translation

### ISSUE THREAD

**Issue by Gaming4LifeDE** [ranfdev/Geopard#40]
**Describe the solution you'd like**
I'd like to help contribute a German translation file. If you prepare the application to accept translation files and provide templates with instructions, I'll do the German translation for you

**Comment by IngrownMink4** [comment]
> **Describe the solution you'd like** I'd like to help contribute a German translation file. If you prepare the application to accept translation files and provide templates with instructions, I'll do the German translation for you

I could also help to translate the app into Spanish and Basque if you use something like Weblate or Crowdin!

**Comment by daudix-UFO** [comment]
I also can translate this project to Russian!

**Comment by ranfdev** [comment]
Replicating this pull request can be a great starting point https://github.com/ranfdev/Geopard/pull/63
