### ISSUE TITLE
Selecting text messes with the styling

### ISSUE THREAD

**Issue by Gaming4LifeDE** [ranfdev/Geopard#41]
**Describe the bug**
When selecting text over multiple lines with different styling, the styling of the "normal" text will change.

**To Reproduce**
1. Drag to select text on heading
2. Move the mouse cursor
3. The selected text will get the wrong styling

**Expected behavior**
The text shouldn't be messing up

**Screenshots**
https://user-images.githubusercontent.com/33233376/173638773-4f704e91-2198-43fd-b437-11c8efc257ed.mp4

**Software info (please complete the following information):**
 - OS: Fedora 36
 - Geopard's Version: git master compiled with Builder

**Page Source if you're interested**
```
# Title

this is a paragraph
this is line 2

* First item
* Second item
* Thrid item
```

**Comment by ranfdev** [comment]
It seems I can't apply a `gtk::TextTag` on a text with "\n" at the end. GTK apparently doesn't like that

**Comment by Gaming4LifeDE** [comment]
Looks like an amazing solution and it should make it possible to implement a ton of new parsers easily (md, json, xml?).

The last release was ages ago, do you think you could prepare a new release?
