### ISSUE TITLE
Geopard won't start (Flatpak)

### ISSUE THREAD

**Issue by Geronymos** [ranfdev/Geopard#43]
**Describe the bug**
The Flatpak version of Geopard won't start. Neither from an application launcher nor from cli. 

**To Reproduce**
- Start Geopard from application launcher (`wofi --show drun`)
- Start Geopard from flatpak-cli (`flatpak run com.ranfdev.Geopard`)
- Error message appears (see additional context)

**Expected behavior**
Geopard should start in a graphical window. 

**Screenshots**
.

**Software info (please complete the following information):**
 - OS: 5.18.3-arch1-1 running sway (Wayland)
 - Geopard's Version: 1.2.0 (with `flatpak info com.ranfdev.Geopard `)

**Additional context**
Error message after running `flatpak start com.ranfdev.Geopard`:

```sh
com.ranfdev.Geopard
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', src/widgets/window.rs:618:80
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Looks like it's this line: https://github.com/ranfdev/Geopard/blob/499670570e5f76d2a5844dc7a6028c1814063d7f/src/widgets/window.rs#L618

I am looking forward on this project since i quite like the minimalism of the gemini protocol. On version 1.1.0 I got a similar issue but it also said something about `xdg.desktop.portal.Settings`.

**Comment by ranfdev** [comment]
Are you overriding the gtk theme of flatpak apps?
Geopard changes the whole app theme depending on the current domain you are visiting. To do so, it relies on the included libadwaita theme as base.
By overriding the theme, Geopard can't find the correct `accent_color`.

That's the only explanation that comes to mind right now.
