### ISSUE TITLE
Scrollbar should be on the window edge

### ISSUE THREAD

**Issue by bertob** [ranfdev/Geopard#5]
The scrollbar is inside the clamp, so it draws a lot of attention and doesn't match the rest of the system, where scrollbars are always on the edge of the view,

![image](https://user-images.githubusercontent.com/1908896/167029134-560f1d19-9d0a-45bf-a82a-5fd3eee8b8c6.png)

**Comment by ranfdev** [comment]
Thank you, I'll see what I can do
