### ISSUE TITLE
Add support for opening files and opening links

### ISSUE THREAD

**Issue by ghost** [ranfdev/Geopard#50]
**Is your feature request related to a problem? Please describe.**
You can not open files or links through a browser or the command line.

**Describe the solution you'd like**
Adding support for opening files and links would solve this problem and make it more accessible instead of needing to copy and paste links into the browser.

**Additional context**
#### Opening a link through the command line
```
$ flatpak run com.ranfdev.Geopard gemini://abcdef.xyz/
com.ranfdev.Geopard

(geopard:2): GLib-GIO-CRITICAL **: 01:30:25.213: This application can not open files.
```

#### Opening a link through the browser
![gemini](https://user-images.githubusercontent.com/101398895/188258883-abecfc96-be61-4dfc-bcac-6209bd12837c.png)

**Comment by tfuxu** [comment]
@ranfdev This issue can be closed
