### ISSUE TITLE
Scrollbar isn't on window edge

### ISSUE THREAD

**Issue by bertob** [ranfdev/Geopard#52]
The scrollbar is in the middle of the window, which looks a bit odd:

![image](https://user-images.githubusercontent.com/1908896/193607525-0b95ee20-f99f-482f-8adb-f83c3439c7c6.png)

**Comment by ranfdev** [comment]
Eh, I know, It's bad, and I tried to change this.
Right now the widget tree is like this: AdwClamp>ScrolledWindow>TextView. Changing the order to ScrolledWindow>AdwClamp>TextView would solve the problem, but that introduces  some bugs in the scrolling behaviour. Example: after a page load, the page would jump to the bottom, and a single scroll would make the scrollbar jump to the top of the page.

GTK has specific code to handle a TextView as a direct child of a ScrolledWindow. Putting an AdwClamp between the two widgets breaks the scrolling of the TextView.


I would like to fix this, but I haven't found a working solution yet.

By the way, you've already reported this issue before at #5

**Comment by bertob** [comment]
> By the way, you've already reported this issue before

Wooops, sorry, I should have checked :see_no_evil: 

Have you tried asking on Matrix in #gtk or #libadwaita? There are apps that do something similar (e.g. Apostrophe), so maybe there are people there who figured this out in their apps.

**Comment by Exalm** [comment]
GtkScrolledWindow -> AdwClampScrollable -> GtkTextView
