### ISSUE TITLE
Move renderer to WebKitGtk

### ISSUE THREAD

**Issue by tfuxu** [ranfdev/Geopard#66]
#### Description
The current solution of using TextView for rendering Gemini documents is quite ingenious I must say, but it also limits things that can be done in Geopard. For example images can't be rendered in normal TextView and long text in preformatted mode makes whole webview horizontally longer (which could be resolved in WebKit by adding a frame to preformatted text with horizontal scrollbar).

WebKitGtk has a broad range of functions and classes which allow for complete customization to make it as integrated in Gtk apps as possible. WebKit has built-in TLS certificates support (access to website's TLS information available in [this](https://webkitgtk.org/reference/webkit2gtk/unstable/method.WebView.get_tls_info.html) function) which would resolve issue #19. It has [find controller](https://webkitgtk.org/reference/webkit2gtk/unstable/class.FindController.html) for implementing text search in WebView (possibly resolves #42). There is also an extensive [Settings](https://webkitgtk.org/reference/webkit2gtk/unstable/class.Settings.html) class which allows to modify or disable almost every feature of WebKit.

For possible implementation, Dev Toolbox and Apostrophe uses WebViewGtk for rendering Markdown preview. For Dev Toolbox implementation, you can look [here](https://github.com/aleiepure/devtoolbox/blob/main/src/widgets/webview_area.py), and [here](https://github.com/aleiepure/devtoolbox/blob/main/src/services/markdown_preview.py) on how it converts Markdown to HTML. For Apostrophe, you can look [here](https://gitlab.gnome.org/World/apostrophe/-/blob/main/apostrophe/preview_web_view.py) and [here](https://gitlab.gnome.org/World/apostrophe/-/blob/main/apostrophe/preview_renderer.py).

**Comment by ranfdev** [comment]
I know WebKit is more powerful, but it's also more resource intensive. 

We are using gemini to stay away from the bloat brought up by the web. I feel WebKit goes against the gemini values.
I'm trying my best to make a lightweight and fast browser that doesn't rely on web technologies.

I won't use WebKit sorry. Thanks anyway for proposing an improvement.

**Comment by tfuxu** [comment]
I agree with your statement, WebKit is a overkill for any Gemini browser and a big bloat because of many features which will never be used in any Gemini website. It can also get more memory intensive than Firefox when many tabs are opened simultaneously (~600MB with 7 tabs of Markdown document converted to HTML).

However, I found an alternative. [GemView](https://codeberg.org/jeang3nie/gemview) is a Gemtext (and not only) GTK 4 renderer written in Rust. It's the same approach as a current Geopard renderer, because it uses an inherited Gtk.TextView widget to render Gemini, Gopher, Finger and Spartan pages. Here's a full [feature list](https://codeberg.org/jeang3nie/gemview#features).

**Comment by ranfdev** [comment]
That's great, thanks for linking it.

I will look and learn from that project, but I'm not going to use it directly.

I'm going forward on another path. I plan on replacing the TextView with a SourceView, like the one used inside the gnome builder IDE.

SourceView extends the TextView by adding search/replace, highlighting, and other useful stuff.
