### ISSUE TITLE
Randomly clicking the content area will cause SIGSEGV

### ISSUE THREAD

**Issue by felinira** [ranfdev/Geopard#80]
**Describe the bug**
I wasn't able to generate a backtrace yet. But randomly (double-)clicking the content area a bit sporadically the client will eventually (after a couple minutes) crash with a segfault.

**To Reproduce**
1. Open a page
2. Sporadically click mouse in the content area a bit
3. SIGSEGV

**Software info (please complete the following information):**
 - OS: Fedora 38
 - Geopard's Version: 1.4.0

**Comment by tfuxu** [comment]
@felinira Can you still reproduce this issue?
