### ISSUE TITLE
Clicking on gemini:// links launches Geopard but doesn't actually load the link

### ISSUE THREAD

**Issue by JonLiuFYI** [ranfdev/Geopard#88]
**Describe the bug**
If I click on a gemini:// link in my browser, Geopard will open as expected, but it just shows the start page, bookmarks.gemini. It doesn't go to the link I actually clicked on.

**To Reproduce**
1. In Firefox, go to https://geminiquickst.art/#where-do-i-point-my-gemini-client
2. Click on the link, gemini://geminiquickst.art/
3. Geopard opens but only shows the start page

**Expected behavior**
Geopard opens and starts loading the URL in question

**Screenshots**
N/A

**Software info (please complete the following information):**
 - OS: Fedora 39
 - Geopard's Version: 1.4.0

**Additional context**
N/A

**Comment by tfuxu** [comment]
Looks like this was somehow fixed, as I can no longer reproduce this.

**Comment by JonLiuFYI** [comment]
Yeah, I just tried now and it worked as expected. No more issue!
