### ISSUE TITLE
Download not working on Flatpak

### ISSUE THREAD

**Issue by asorander** [ranfdev/Geopard#9]
I've installed Geopard Flatpak on flathub and downloads won't start. 
If you click a link (Konpeito's  tape (gemini://konpeito.media/index.gmi), for example) the page will change for a never ending loading and nothing happens.

**Comment by ranfdev** [comment]
That's strange. Somehow the file downloading functionality got broken. Thanks for the report, I'll fix it

**Comment by ranfdev** [comment]
It's fixed. You can update Geopard :)
